version: '3.7'

networks:
    books:
        external: false

services:
    books-db:
        image: postgres:12-alpine
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: books
            POSTGRES_DB: books
        volumes:
            - "books-db:/var/lib/postgresql/data"
        networks:
            - books
    web:
        build:
            context: ../..
            dockerfile: ./docker/development/Dockerfile
        volumes:
            - ../../:/app
            - "web-packages:/usr/local/lib/python3.8/site-packages"
            - "web-bin:/usr/local/bin"
        networks:
            - books
        environment:
            DATABASE_URI: postgresql://books:secret@books-db:5432/books
        working_dir: /app
        ports:
            - 8001:8001
        command: '/app/tools/run-backend.sh'
        depends_on:
            - books-db

volumes:
    web-packages:
    web-bin:
    books-db:
